name: Build and deploy

on:
  workflow_run:
    workflows: [Test]
    branches: [master]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: insektionen/cleaning-list-fe:latest
      - name: Export container
        run: docker save insektionen/cleaning-list-fe:latest | gzip > cleaning-list-fe_latest.tar.gz
      - name: Copy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: 'cleaning-list-fe_latest.tar.gz'
          target: '~/'
      - name: Import and start on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: docker load < cleaning-list-fe_latest.tar.gz && cd cleaning-list-fe && docker-compose up -d
